name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install && npm run install:ui
      - name: lint
        run: npm run lint && npm run lint:ui
      - name: build
        run: npm run build
      - name: test
        run: npm test && npm run test:ui
        env:
          TEST_MONGODB_URI: ${{secrets.TEST_MONGODB_URI}}
          SECRET: ${{secrets.SECRET}}
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start:test
          wait-on: http://localhost:3001
        env:
          TEST_MONGODB_URI: ${{secrets.TEST_MONGODB_URI}}
          SECRET: ${{secrets.SECRET}}
      - name: deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ', '), '#skip')}}
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "blog-with-actions"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          healthcheck: "https://blog-with-actions.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@eca2b69f9e2c24be7decccd0f15fdb1ea5906598
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ', '), '#skip')}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: master
      - name: Build failure Slack message
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,took
          icon_emoji: ':no_entry:'
          channel: '#code'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: ${{ failure() }}
      - name: Deployment success Slack message
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: commit,author,took
          channel: '#code'
          custom_payload: |
            {
              icon_emoji: ':white_check_mark:',
              attachments: [{
                color: 'good',
                text: `A new version deployed to https://pokedex-through-pipeline.herokuapp.com (${process.env.AS_COMMIT}) by ${process.env.AS_AUTHOR} Build took ${process.env.AS_TOOK}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ', '), '#skip') && success() }}